# For local server (useless now 'cause the database has been shifted to supabase with different credentials)

version: "3.8"
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ankur@6261
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  
  adminer: 
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_USERNAME: postgres
      ADMINER_DEFAULT_PASSWORD: ankur@6261
      ADMINER_DEFAULT_DATABASE: postgres
