version: "3.8"
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shop_swift
    ports:
      - "5432:5432"
  
  adminer: 
    image: adminer
    restart: always
    ports:
      - 8080:8080